### ISSUE TITLE
Crashes as soon as it starts

### ISSUE THREAD

**Issue by DrHojo123** [File-New-Project/EarTrumpet#1107]
### Summary

I used this before and worked fine until today. Gives no error code each time I click it and view if it even loads task manger I see it for a second then goes off.

I did find another issue like this so I checked the event viewer and have a Application Error and .NET Runtime error which I will post below

### Steps to reproduce

Uninstalled and reinstalled from Microsoft Store clicked open nothing loads.

### EarTrumpet version

2.1.10.0

### Windows version

10.0.22000.556

### Additional information

Application Error:
Faulting application name: EarTrumpet.exe, version: 2.1.10.0, time stamp: 0x623ff65b
Faulting module name: KERNELBASE.dll, version: 10.0.22000.527, time stamp: 0xc2abc35e
Exception code: 0xe0434352
Fault offset: 0x0013ece2
Faulting process ID: 0x30bc
Faulting application start time: 0x01d84389ea420bb3
Faulting application path: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.1.10.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report ID: c364ec8f-0351-483e-ac64-311a8f29721d
Faulting package full name: 40459File-New-Project.EarTrumpet_2.1.10.0_x86__1sdd7yawvg6ne
Faulting package-relative application ID: EarTrumpet

.NET Runtime Error:
Application: EarTrumpet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException
   at System.Reflection.MetadataImport._Enum(IntPtr, Int32, Int32, System.Reflection.MetadataEnumResult ByRef)
   at System.Reflection.RuntimeParameterInfo.GetParameters(System.IRuntimeMethodInfo, System.Reflection.MemberInfo, System.Signature, System.Reflection.ParameterInfo ByRef, Boolean)
   at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
   at System.RuntimeType.FilterApplyMethodBase(System.Reflection.MethodBase, System.Reflection.BindingFlags, System.Reflection.BindingFlags, System.Reflection.CallingConventions, System.Type[])
   at System.RuntimeType.GetConstructorCandidates(System.String, System.Reflection.BindingFlags, System.Reflection.CallingConventions, System.Type[], Boolean)
   at System.RuntimeType.GetConstructorImpl(System.Reflection.BindingFlags, System.Reflection.Binder, System.Reflection.CallingConventions, System.Type[], System.Reflection.ParameterModifier[])
   at System.Type.GetConstructor(System.Reflection.BindingFlags, System.Reflection.Binder, System.Type[], System.Reflection.ParameterModifier[])
   at System.Security.Principal.WindowsIdentity..cctor()

Exception Info: System.TypeInitializationException
   at System.Security.Principal.WindowsIdentity.Impersonate(IntPtr)
   at System.Configuration.ClientConfigurationHost.Impersonate()
   at System.Configuration.BaseConfigurationRecord.Impersonate()
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   at System.Configuration.ClientConfigurationSystem.EnsureInit(System.String)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.GetSection(System.String)
   at System.Configuration.PrivilegedConfigurationManager.GetSection(System.String)
   at System.Diagnostics.DiagnosticsConfiguration.GetConfigSection()
   at System.Diagnostics.DiagnosticsConfiguration.Initialize()
   at System.Diagnostics.DiagnosticsConfiguration.get_IndentSize()
   at System.Diagnostics.TraceInternal.InitializeSettings()
   at System.Diagnostics.TraceInternal.get_Listeners()
   at System.Diagnostics.Trace.get_Listeners()
   at EarTrumpet.Diagnosis.ErrorReporter..ctor(EarTrumpet.AppSettings)
   at EarTrumpet.App.OnAppStartup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at EarTrumpet.App.Main()

**Comment by riverar** [comment]
@DrHojo123 That's not good :(

Do you use MSI Afterburner? (https://github.com/File-New-Project/EarTrumpet/issues/268) Or Rivatuner? (https://github.com/File-New-Project/EarTrumpet/issues/536)

If not, please do the following:

1. Open Regedit, navigate to `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`
2. Create a REG_DWORD value named `DumpType` and give it a value of 2
3. Reproduce the crash
4. Find the EarTrumpet.exe.dmp in %LOCALAPPDATA%\CrashDumps, zip it up and upload it to OneDrive/send a copy to team@eartrumpet.app. (Do not attach it here‼️)
5. Repeat step 1 above then delete `DumpType` to clean up

Thanks!

**Comment by DrHojo123** [comment]
I sent the email to you with the dmp file linked by a onedrive.

**Comment by riverar** [comment]
Got it, looking now.

**Comment by riverar** [comment]
Apologies if this sounds like generic Windows advice, but .NET looks legit broken on this machine. Can you open an administrative command prompt and run `sfc /scannow`? Let's see if it finds anything.

**Comment by DrHojo123** [comment]
That's strange considering I just reformatted it a few weeks ago, but ya I will do that now and will reply when it's done

**Comment by DrHojo123** [comment]
I got this

Windows Resource Protection found corrupt files but was unable to fix some of them.
For online repairs, details are included in the CBS log file located at
windir\Logs\CBS\CBS.log. For example C:\Windows\Logs\CBS\CBS.log. For offline
repairs, details are included in the log file provided by the /OFFLOGFILE flag.

I even did a Dism /Online /Cleanup-Image /ScanHealth and that went through fine I think

**Comment by riverar** [comment]
Interesting. I'm curious what's in that log -- anything .NET/CLR related? Any assemblies? Can attach the log here too if you'd wish. Sounds bad tho, not going to lie. 💀

**Comment by DrHojo123** [comment]
[CBS.log](https://github.com/File-New-Project/EarTrumpet/files/8375699/CBS.log)

Feel free to look and I believe you. The strangest thing it started to happen when I deleted temp files on my PC that had old windows files which I've done in future before shouldn't cause issues so no idea if it's just timing or something in the old windows files was still acting as dominant.

**Comment by riverar** [comment]
Yep this is why.

```
...
2022-03-30 00:44:00, Info                  CSI    0000026e Hashes for file member [l:15]'mscorlib.ni.dll' do not match.
 Expected: {l:20 b:25a430129d85f96389c78d724c901c309c46b55a}.
 Actual: {l:20 b:d9d985b9e60ed682be13a11837c0282617272321}.
2022-03-30 00:44:00, Info                  CSI    0000026f [SR] Could not reproject corrupted file \??\C:\Windows\Microsoft.NET\Framework\v4.0.30319\NativeImages\\mscorlib.ni.dll; source file in store is also corrupted
2022-03-30 00:44:00, Info                  CSI    00000270 Hashes for file member [l:12]'mingliub.ttc' do not match.
 Expected: {l:32 ml:33 b:814fc6cc5407d2137022a1ff8587cfa43d5a2736b2ab5378ea49ceb5c072de37}.
 Actual: {l:32 b:7333f0996d1a1b70adb6eebb02af8ff130f32d2b382230883ca3f3a4c288ddc7}.
...
```

As to fixing this, there's some guidance at [Microsoft Support](https://support.microsoft.com/en-us/topic/use-the-system-file-checker-tool-to-repair-missing-or-corrupted-system-files-79aa86cb-ca52-166a-92a3-966e85d4094e#:~:text=how%20to%20manually%20replace%20a%20corrupted%20system%20file%20with%20a%20known%20good%20copy%20of%20the%20file). You'll need to get clean copies of:
```
C:\Windows\Fonts\mingliub.ttc
C:\Windows\Microsoft.NET\Framework\v4.0.30319\NativeImages\mscorlib.ni.dll
C:\Windows\Speech_OneCore\Engines\SR\en-US-N\lsr1033.lxa
C:\Windows\SystemApps\Microsoft.AAD.BrokerPlugin_cw5n1h2txyewy\AAD.Core.dll
```

**Comment by DrHojo123** [comment]
At least something was found, now the problem is where do I go to find clean ones.

I appreciate the help by the way.

**Comment by riverar** [comment]
I think I have a `10.0.22000.556` box handy, let me check. If so, I'll attach a zip with the files.

**Comment by DrHojo123** [comment]
Go ahead and and take your time.

**Comment by riverar** [comment]
Shout out to @GoldenTao for the assist. Here you go:
[files.zip](https://github.com/File-New-Project/EarTrumpet/files/8375854/files.zip)

**Comment by DrHojo123** [comment]
Password protected

**Comment by riverar** [comment]
@DrHojo123 `issue1107`

**Comment by riverar** [comment]
Closing this issue for now as it's not directly related to EarTrumpet (before I forget), but feel free to continue the discussion.

**Comment by DrHojo123** [comment]
Good man!! Doing that fixed the issue! able to use Eartrumpet once again thanks for the help!

**Comment by riverar** [comment]
We accept VISA and Mastercard.
