### ISSUE TITLE
Stop using ColorPrevalence and start using Windows.UI.ViewManagement.UISettings

### ISSUE THREAD

**Issue by Idearum** [File-New-Project/EarTrumpet#116]
So I'm not certain what exactly triggered the below error. I've been playing around with Stardock's WindowBlinds the last couple of days (blurred glass!) so it's probably that one that might've caused it. But even unloaded/disabled I continue to get the error message, and I've tried to change the accent color of Windows 10 as well as restarting EarTrumpet. Didn't do a thing.

Anyway, the error dialog opens when I left-click the EarTrumpet icon in the notification area. The right-click menu is accessible, but that's about it.

**Specs:**
Win10 Creators Update v1703 (build 15063.13)
EarTrumpet 1.4.4.0

**Details:**
```************** Exception Text **************
System.InvalidCastException: Specified cast is not valid.
   at EarTrumpet.Services.UserSystemPreferencesService.get_UseAccentColor()
   at EarTrumpet.Services.ThemeService.GetWindowBackgroundColor()
   at EarTrumpet.Services.ThemeService.UpdateThemeResources(ResourceDictionary dictionary)
   at EarTrumpet.MainWindow.UpdateTheme()
   at EarTrumpet.MainWindow.TrayIcon_Invoked()
   at System.Action.Invoke()
   at EarTrumpet.TrayIcon.TrayIcon_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
EarTrumpet
    Assembly Version: 1.4.4.0
    Win32 Version: 1.4.4.0
    CodeBase: file:///C:/Program%20Files/WindowsApps/40459File-New-Project.EarTrumpet_1.4.4.0_x86__1sdd7yawvg6ne/EarTrumpet.exe
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
PresentationFramework.Aero2
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
UIAutomationTypes
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/UIAutomationTypes/v4.0_4.0.0.0__31bf3856ad364e35/UIAutomationTypes.dll
----------------------------------------```

**Comment by riverar** [comment]
Thanks. Not sure what's causing this, but this is a great time to replace that code with better supported method of getting the accent color (Windows.UI.ViewManagement.UISettings)

**Comment by Idearum** [comment]
I believe I have at least found out where the InvalidCastException comes from. For some reason the registry key "ColorPrevalence" isn't of a REG_DWORD type but of a REG_SZ with a value of 0. Toggling "Show accent color on the following surfaces" in the Settings -> Personalization app recreated the registry key correctly and solved the issue.

![](http://i.imgur.com/rL9sBZT.png)

I haven't tracked down what's causing it yet, but the suspect is most likely Stardock's WindowBlinds 10.6 as I mentioned previously. Screwing around so much with the DWM is bound to include a few bugs here and there.

**Comment by riverar** [comment]
Fixed in next release of WindowBlinds https://forums.stardock.com/482553/page/1/#3686610, will leave this open as a bug to track us changing this infrastructure to the official UWP APIs mentioned earlier.

**Comment by riverar** [comment]
Closing this as wontfix. The WinRT API isn't as helpful as initially thought.
