### ISSUE TITLE
Description: The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by bugz434** [File-New-Project/EarTrumpet#1540]
### Summary

Application: EarTrumpet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr)
   at Windows.ApplicationModel.Package.get_Current()
   at EarTrumpet.Interop.Helpers.PackageHelper.CheckHasIdentity()
   at EarTrumpet.App.OnAppStartup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at EarTrumpet.App.Main()

Faulting application name: EarTrumpet.exe, version: 2.3.0.0, time stamp: 0x64cfe711
Faulting module name: KERNELBASE.dll, version: 10.0.22621.3447, time stamp: 0x67ef8931
Exception code: 0xe0434352
Fault offset: 0x001498b2
Faulting process id: 0x0x65B0
Faulting application start time: 0x0x1DA92EE12DC7E5E
Faulting application path: C:\Program Files\WindowsApps\40459File-New-Project.EarTrumpet_2.3.0.0_x86__1sdd7yawvg6ne\EarTrumpet\EarTrumpet.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: c1c55eef-c032-414a-a308-0df4e75105cb
Faulting package full name: 40459File-New-Project.EarTrumpet_2.3.0.0_x86__1sdd7yawvg6ne
Faulting package-relative application ID: EarTrumpet

### Steps to reproduce

run eartrumpet

### EarTrumpet version

cant check wont open. latest from windows store

### Windows version

10.0.22631.3447

### Additional information

try to run eartrumpet and this happens.  wont open. just started happening randomly . tried reinstalling. no go.

**Comment by riverar** [comment]
@bugz434 Thanks for the report. Is there anything out of the ordinary with this install of Windows? Did you run any sort of privacy focused scripts? Debloaters? etc? Not blaming you, just trying to get to the root cause here.

**Comment by bugz434** [comment]
no its a fresh install of windows about a week old now,  just did a windows update and noticed eartrumpet wasn't launched, and when i tried to open it, it wouldn't launch.

**Comment by riverar** [comment]
@bugz434 Can you uninstall EarTrumpet and install a dev version? https://install.eartrumpet.app/dev/EarTrumpet.Package.appinstaller

That still crashes for you, right?
