### ISSUE TITLE
Apps don't show after switching mono audio On/Off

### ISSUE THREAD

**Issue by amogusmogu2** [File-New-Project/EarTrumpet#1544]
### Summary

whenever switching windows-mono-audio on/off apps don't show up in the mixer, and you'd have to restart EarTrumpet to see them again 
![image](https://github.com/File-New-Project/EarTrumpet/assets/162755561/83460bec-c69b-4d7a-badf-b32ce6e30890)
![image](https://github.com/File-New-Project/EarTrumpet/assets/162755561/d9bde834-5e15-441d-8e62-6d803ae12a19)

### Steps to reproduce

turn on/off mono audio
bug happens

### EarTrumpet version

2.3.0.0

### Windows version

1000.22688.1000.0

### Additional information

not sure if this helps, but I'll add it too.

version: 2.3.0.0
runtimeMinutes: 7
gdiObjects: 44
userObjects: 43
globalGdiObjects: 1597
globalUserObjects: 1597
handleCount: 646
releaseStage: production
osVersionBuild: 22621.1.amd64fre.ni_release.220506-1250
osArchitecture: 64 bit
processorCount: 6 core(s)
IsLightTheme: False
IsSystemLightTheme: False
IsRTL: False
IsTransparencyEnabled: False
UseAccentColor: False
AnimationsEnabled: False
IsHighContrast: False
HasIdentity: True
IsShuttingDown: False
Culture: en-AE
CurrentUICulture: en-US
systemDpi: 96
taskbarDpi: 96
addons: 
region: AE
--------------------------------------------------------------------
(Default Device) Speakers (Realtek(R) Audio) 50% Id: {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}
--------------------------------------------------------------------
Virtual Speakers (Virtual Speakers for AudioRelay) 100% Id: {0.0.0.00000000}.{f97649f8-6062-47ba-8a0d-04a4423ae68d}
--------------------------------------------------------------------
13:46:51.494 UI AudioDeviceManager-(Playback) Create
13:46:51.498 UI AudioDeviceManager-(Playback) Create Exit
13:46:51.503 UI TaskbarIconSource Changed: kind=NoDevice dpi=96 isSysLight=False isLegacy=False
13:46:51.510  3   AudioDeviceManager-(Playback) OnDeviceAdded {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}
13:46:51.510 UI IconHelper LoadIconForTaskbar C:\Windows\System32\SndVolSSO.dll,125 16x16
13:46:51.512  3   AudioDevice Create {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}
13:46:51.558  3   AudioDeviceSession Create Spotify {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|\Device\HarddiskVolume4\Users\hamog\AppData\Roaming\Spotify\Spotify.exe%b{00000000-0000-0000-0000-000000000000}|1%b10500
13:46:51.564  3   AudioDeviceSession Create *SystemSounds {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:46:51.714 UI FlyoutViewModel ChangeState Hidden
13:46:51.716  3   AudioDeviceManager-(Playback) OnDeviceAdded {0.0.0.00000000}.{f97649f8-6062-47ba-8a0d-04a4423ae68d}
13:46:51.717  3   AudioDevice Create {0.0.0.00000000}.{f97649f8-6062-47ba-8a0d-04a4423ae68d}
13:46:51.720  3   AudioDeviceSession Create *SystemSounds {0.0.0.00000000}.{f97649f8-6062-47ba-8a0d-04a4423ae68d}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:46:51.723 UI AudioDeviceManager-(Playback) QueryDefaultDevice
13:46:51.727 UI TaskbarIconSource Changed: kind=SpeakerTwoBars dpi=96 isSysLight=False isLegacy=False
13:46:51.727 UI IconHelper LoadIconForTaskbar C:\Windows\System32\SndVolSSO.dll,123 16x16
13:46:51.737 UI AddonResolver Load
13:46:51.750 UI ShellNotifyIcon IsVisible True
13:46:51.752 UI AudioDeviceSessionCollection AddSession Spotify {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|\Device\HarddiskVolume4\Users\hamog\AppData\Roaming\Spotify\Spotify.exe%b{00000000-0000-0000-0000-000000000000}|1%b10500
13:46:51.753 UI AudioDeviceSessionCollection AddSession *SystemSounds {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:46:51.755 UI AudioDeviceSessionCollection AddSession *SystemSounds {0.0.0.00000000}.{f97649f8-6062-47ba-8a0d-04a4423ae68d}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:46:51.805 UI ImageEx LoadImage 24x24 C:\Windows\sysnative\audiosrv.dll,203
13:46:51.813 UI ImageEx LoadImage 24x24 C:\Windows\sysnative\audiosrv.dll,203
13:46:51.835 UI ImageEx LoadShellIcon 24x24 C:\Users\hamog\AppData\Roaming\Spotify\Spotify.exe
13:50:03.108 UI FlyoutViewModel ChangeState Opening
13:50:03.114 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=131610, Size=[Left=0,Top=1032,Right=1920,Bottom=1080], Monitor=Screen[Bounds={X=0,Y=0,Width=1920,Height=1080} WorkingArea={X=0,Y=0,Width=1920,Height=1032} Primary=True DeviceName=\\.\DISPLAY1
13:50:03.134 UI FlyoutViewModel ChangeState Open
13:52:31.744  8   AudioDeviceSession OnStateChanged Active *SystemSounds {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:52:33.087  8   AudioDeviceSession OnStateChanged Inactive *SystemSounds {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:52:55.491  8   AudioDeviceSession OnStateChanged Inactive Spotify {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|\Device\HarddiskVolume4\Users\hamog\AppData\Roaming\Spotify\Spotify.exe%b{00000000-0000-0000-0000-000000000000}|1%b10500
13:52:55.492  8   AudioDeviceSession DisconnectSession Spotify {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|\Device\HarddiskVolume4\Users\hamog\AppData\Roaming\Spotify\Spotify.exe%b{00000000-0000-0000-0000-000000000000}|1%b10500
13:52:55.492  8   AudioDeviceSession DisconnectSession *SystemSounds {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:52:55.493  8   AudioDeviceSession DisconnectSession *SystemSounds {0.0.0.00000000}.{f97649f8-6062-47ba-8a0d-04a4423ae68d}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:52:55.493 UI AudioDeviceSessionCollection RemoveSession Spotify {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|\Device\HarddiskVolume4\Users\hamog\AppData\Roaming\Spotify\Spotify.exe%b{00000000-0000-0000-0000-000000000000}|1%b10500
13:52:55.495 UI AudioDeviceSessionCollection RemoveSession *SystemSounds {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:52:55.496 UI AudioDeviceSessionCollection RemoveSession *SystemSounds {0.0.0.00000000}.{f97649f8-6062-47ba-8a0d-04a4423ae68d}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:52:55.497 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=131610, Size=[Left=0,Top=1032,Right=1920,Bottom=1080], Monitor=Screen[Bounds={X=0,Y=0,Width=1920,Height=1080} WorkingArea={X=0,Y=0,Width=1920,Height=1032} Primary=True DeviceName=\\.\DISPLAY1
13:52:55.502 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=131610, Size=[Left=0,Top=1032,Right=1920,Bottom=1080], Monitor=Screen[Bounds={X=0,Y=0,Width=1920,Height=1080} WorkingArea={X=0,Y=0,Width=1920,Height=1032} Primary=True DeviceName=\\.\DISPLAY1
13:52:55.503 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=131610, Size=[Left=0,Top=1032,Right=1920,Bottom=1080], Monitor=Screen[Bounds={X=0,Y=0,Width=1920,Height=1080} WorkingArea={X=0,Y=0,Width=1920,Height=1032} Primary=True DeviceName=\\.\DISPLAY1
13:52:55.567  8   AudioDeviceSession OnStateChanged Active Spotify {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|\Device\HarddiskVolume4\Users\hamog\AppData\Roaming\Spotify\Spotify.exe%b{00000000-0000-0000-0000-000000000000}|1%b10500
13:52:55.567  9   AudioDeviceSessionCollection OnSessionCreated
13:52:55.571  9   AudioDeviceSessionCollection CreateAndAddSession System.Runtime.InteropServices.COMException (0x88890004): Exception from HRESULT: 0x88890004
   at EarTrumpet.Interop.MMDeviceAPI.IChannelAudioVolume.GetChannelCount()
   at EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSessionChannelCollection..ctor(IChannelAudioVolume session, Dispatcher dispatcher) in D:\a\EarTrumpet\EarTrumpet\EarTrumpet\DataModel\WindowsAudio\Internal\AudioDeviceSessionChannelCollection.cs:line 14
   at EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSession..ctor(IAudioDevice parent, IAudioSessionControl session, Dispatcher foregroundDispatcher) in D:\a\EarTrumpet\EarTrumpet\EarTrumpet\DataModel\WindowsAudio\Internal\AudioDeviceSession.cs:line 151
   at EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSessionCollection.CreateAndAddSession(IAudioSessionControl session) in D:\a\EarTrumpet\EarTrumpet\EarTrumpet\DataModel\WindowsAudio\Internal\AudioDeviceSessionCollection.cs:line 68
13:53:01.128  9   AudioDeviceSession OnStateChanged Active *SystemSounds {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:53:01.128  8   AudioDeviceSessionCollection OnSessionCreated
13:53:01.128  8   AudioDeviceSessionCollection CreateAndAddSession System.Runtime.InteropServices.COMException (0x88890004): Exception from HRESULT: 0x88890004
   at EarTrumpet.Interop.MMDeviceAPI.IChannelAudioVolume.GetChannelCount()
   at EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSessionChannelCollection..ctor(IChannelAudioVolume session, Dispatcher dispatcher) in D:\a\EarTrumpet\EarTrumpet\EarTrumpet\DataModel\WindowsAudio\Internal\AudioDeviceSessionChannelCollection.cs:line 14
   at EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSession..ctor(IAudioDevice parent, IAudioSessionControl session, Dispatcher foregroundDispatcher) in D:\a\EarTrumpet\EarTrumpet\EarTrumpet\DataModel\WindowsAudio\Internal\AudioDeviceSession.cs:line 151
   at EarTrumpet.DataModel.WindowsAudio.Internal.AudioDeviceSessionCollection.CreateAndAddSession(IAudioSessionControl session) in D:\a\EarTrumpet\EarTrumpet\EarTrumpet\DataModel\WindowsAudio\Internal\AudioDeviceSessionCollection.cs:line 68
13:53:02.477  8   AudioDeviceSession OnStateChanged Inactive *SystemSounds {0.0.0.00000000}.{4b5fa160-f5bd-4da0-a78b-8e44b3295d5a}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
13:53:54.352 UI ShellNotifyIcon ShowContextMenu
13:53:54.406 UI ShellNotifyIcon ContextMenu.Opened
13:53:57.212 UI SettingsWindow .ctor
13:53:57.326 UI FlyoutViewModel ChangeState Closing_Stage1
13:53:57.383 UI ShellNotifyIcon ContextMenu.Closed
13:53:57.388 UI FlyoutViewModel ChangeState Closing_Stage2
13:53:57.706 UI FlyoutViewModel ChangeState Hidden

**Comment by detfusco** [comment]
@riverar This issue still persists in EarTrumpet 2.3.0. 

I use an AutoHotkey script to toggle mono audio on and off when I’m using only one of my AirPods. The script simply automates opening "Ease of Access Audio Settings" and moving my cursor to toggle “Turn on mono audio", nothing fancy.
After enabling mono audio, EarTrumpet becomes completely unusable for volume mixing. App volumes disappear altogether. The only way to restore normal behavior is to terminate and relaunch EarTrumpet.

Please see the demo video for a reproduction of the issue: https://youtu.be/x75dUeqb8Aw
