### ISSUE TITLE
When Using SKype Translator It displays an issue.

### ISSUE THREAD

**Issue by MIGMLG** [File-New-Project/EarTrumpet#17]

**Comment by riverar** [comment]
Missing stack dump:

System.IO.FileNotFoundException: Could not find file 'C:\Program Files\WindowsApps\Microsoft.SkypeTranslatorPreview_5.1.0.245_x86__kzf8qxf38zg5c\images\skypeSmall.scale-100.png'.
File name: 'C:\Program Files\WindowsApps\Microsoft.SkypeTranslatorPreview_5.1.0.245_x86__kzf8qxf38zg5c\images\skypeSmall.scale-100.png'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
   at System.Windows.Media.Imaging.BitmapDecoder.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy, Boolean insertInDecoderCache)
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at System.Windows.Media.Imaging.BitmapImage..ctor(Uri uriSource, RequestCachePolicy uriCachePolicy)
   at EarTrumpet.ViewModels.AppItemViewModel..ctor(IAudioMixerViewModelCallback callback, EarTrumpetAudioSessionModelGroup sessions)
   at EarTrumpet.ViewModels.AudioMixerViewModel.<Refresh>b__0(EarTrumpetAudioSessionModelGroup x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at EarTrumpet.ViewModels.AudioMixerViewModel.Refresh()
   at EarTrumpet.MainWindow.TrayIcon_Invoked()
   at System.Action.Invoke()
   at EarTrumpet.TrayIcon.TrayIcon_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.NotifyIcon.OnMouseClick(MouseEventArgs mea)
   at System.Windows.Forms.NotifyIcon.WmMouseUp(Message& m, MouseButtons button)
   at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by riverar** [comment]
We put in a temporary hack to prevent the app from crashing but will continue to work on calling the Resource Manager to parse PRIs
