### ISSUE TITLE
EarTrumpet Starts & Stops In Task Manager Immediately 

### ISSUE THREAD

**Issue by LeoJT54** [File-New-Project/EarTrumpet#334]
EarTrumpet worked fine on several Insider Preview Builds of 1809 but after a Clean install of  the Retail Build 1809 17763.316 I don't see anything on the screen.
I watch Task Manager while launching EarTrumpet only to see it start & stop Immediately. 
I've attached 1 of the many Win Error Reports made after every unsuccessful launch.
I hope you can help solve this issue because this app is far superior to the earlier Windows installation version 1.3.2.0. 

[EarTrumpet Crash Report.Zip](https://github.com/File-New-Project/EarTrumpet/files/2876531/EarTrumpet.Crash.Report.Zip)

**Comment by riverar** [comment]
Thanks @LeoJT54, do you see any corresponding .NET crashes in the Application event log? Should give us more insight.

**Comment by riverar** [comment]
@LeoJT54 Any updates?

**Comment by jmdajm7** [comment]
I seem to have the same problem, i have attached the Application and .NET Runtime crash logs

[EarTrumpet_Crash.zip](https://github.com/File-New-Project/EarTrumpet/files/2896093/EarTrumpet_Crash.zip)

**Comment by Warmfish** [comment]
Same problem. Started today. No updates in Windows 10 for a while. Found this after the crash:

Application: EarTrumpet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
   at System.Number.ParseDouble(System.String, System.Globalization.NumberStyles, System.Globalization.NumberFormatInfo)
   at EarTrumpet.UI.Themes.BrushValueParser.ParseOpacityFromColor(System.String, Double ByRef)
   at EarTrumpet.UI.Themes.BrushValueParser.Parse(System.Windows.DependencyObject, System.String)
   at EarTrumpet.UI.Themes.BrushValueParser.FindReference(System.Windows.DependencyObject, System.String, System.Windows.Media.SolidColorBrush ByRef)
   at EarTrumpet.UI.Themes.BrushValueParser.Parse(System.Windows.DependencyObject, System.String)
   at EarTrumpet.UI.Views.DialogWindow.OnSourceInitialized(System.Object, System.EventArgs)
   at System.EventHandler.Invoke(System.Object, System.EventArgs)
   at System.Windows.Window.OnSourceInitialized(System.EventArgs)
   at System.Windows.Window.CreateSourceWindow(Boolean)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(System.Object)
   at System.Windows.Window.Show()
   at EarTrumpet.App.MaybeShowFirstRunExperience()
   at EarTrumpet.App.DoAppStartup()
   at EarTrumpet.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   at System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at EarTrumpet.App.Main()

**Comment by GoldenTao** [comment]
@Warmfish Looks like you're having a different issue to others in this thread. Thanks for the report, we have a fix ready, it's currently going through Windows Store certification.

**Comment by Warmfish** [comment]
That is absolutely super news!! EarTrumpet is the most useful tool I have when it comes to sound.

**Comment by riverar** [comment]
@LeoJT54 Closing this due to inactivity. Give 2.1.1.0 in the Store a whirl and report back if you still have issues. Thanks!
