### ISSUE TITLE
Eartrumpet keeps crashing

### ISSUE THREAD

**Issue by neetch1** [File-New-Project/EarTrumpet#360]
Im using windows 10 pro and eartrumpet keeps crashing for me and i constantly have to reopen it. It happens every 1-2 hours. Its a great app so would be nice to see a fix for this

**Comment by davuxcom** [comment]
Open Event Viewer (Win+X, Event Viewer), navigate to Windows Logs \ Application, on the left.

In the list, find under "Source" an entry named ".NET Runtime" and select it.  You should see something like:

Application: EarTrumpet.exe
Framework Version: v4.0.30319
.... a stacktrace of the crash...

Paste it all here and we can identity what is crashing.

**Comment by riverar** [comment]
@neetch1 Any updates? Would like to get to the bottom of this before our next release.

**Comment by neetch1** [comment]
Application: EarTrumpet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.OutOfMemoryException
   at System.Windows.Media.Composition.DUCE+Channel.SyncFlush()
   at System.Windows.Media.MediaContext.CompleteRender()
   at System.Windows.Interop.HwndTarget.OnResize()
   at System.Windows.Interop.HwndTarget.HandleMessage(MS.Internal.Interop.WindowMessage, IntPtr, IntPtr)
   at System.Windows.Interop.HwndSource.HwndTargetFilterMessage(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)

**Comment by neetch1** [comment]
here you go, looking forward to next release

**Comment by davuxcom** [comment]
This stack is seemingly indicative of an issue with WPF or your graphics card software.  Could you please check to see if there is a new driver available for your graphics card?

It's also possible that this is a real memory leak - before EarTrumpet crashes, do you observe a high level of memory usage attributed to EarTrumpet in task manager?

**Comment by neetch1** [comment]
I always keep my graphics updated and earthrumpet is using 5,988 K memory

**Comment by davuxcom** [comment]
Thanks - Raf mentions that this is the handle leak he's already fixed up, so you should see this alleviated in the next release.

**Comment by neetch1** [comment]
Awesome thanks

**Comment by riverar** [comment]
@neetch1 Are you still seeing this behavior with our latest update?

**Comment by neetch1** [comment]
Nope it works perfect now thanks for the update
