### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by bramborman** [File-New-Project/EarTrumpet#546]
I tried compiling EarTrumpet to try some stuff but am unable to do so even though I've followed the [Compilation Guide][guide].

[guide]: https://github.com/File-New-Project/EarTrumpet/blob/master/COMPILING.md

My setup is as follows:
- Visual Studio 2019 (16.7.1)
- Git for Windows (2.28.0.windows.1)
- Windows 10 2004
- .NET Framework 4.8 SDK and .NET Framework 4.6.2 targeting pack installed through VS Installer
- Windows 10 SDK from the link in the Compilation Guide

To test this again I did `git clean -dxf` and made sure I have no changes compared to the `dev` branch here so I should be in a _clean environment_.

But as always, I get some errors... I guess the first two are the same issue just being emitted twice and the third is not something to break a build like this. I **am** able to compile the app when I remove the _UtilPack.NuGet.MSBuild_ package and its dependants but that's just a partial workaround. I tried installing the .NET Framework 4.6.2 Developer Pack but it didn't make any change.

I think the problem is in the _UtilPack.NuGet.MSBuild_ package but I'm wondering how can it work for you or in the CI. I'm wondering whether do you plan to upgrade to .NET Core as that would kinda bypass this issue I guess as it has _System.ValueTuple_ built-in.

<details>
<summary>Click to expand</summary>
<p>

```
Exception in initialization: System.IO.FileNotFoundException: Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at UtilPack.NuGet.MSBuild.TaskReferenceHolder..ctor(Object task, String msbuildFrameworkAssemblyName, Boolean taskUsesDynamicLoading)
   at UtilPack.NuGet.MSBuild.TaskReferenceCreator.CreateTaskReferenceHolder(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, String msbuildFrameworkAssemblyName, ResolverLogger logger)
   at UtilPack.NuGet.MSBuild.TaskReferenceCreator.CreateTaskReferenceHolder(String taskTypeName, NuGetAssemblyResolver resolver, String packageID, String packageVersion, String assemblyPath, String msbuildFrameworkAssemblyName, ResolverLogger logger)
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.CreateExecutionHelper(String taskName, XElement taskBodyElement, String taskPackageID, String taskPackageVersion, String taskAssemblyFullPath, String taskAssemblyPathHint, BoundRestoreCommandUser restorer, ResolverLogger resolverLogger, GetFileItemsDelegate getFiles, String assemblyCopyTargetFolder, AppDomainSetup& appDomainSetup)
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.<>c__DisplayClass35_5.<Initialize>b__7()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at UtilPack.ReadOnlyResettableLazy`1.get_Value()
   at UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory.Initialize(String taskName, IDictionary`2 parameterGroup, String taskBody, IBuildEngine taskFactoryLoggingHost)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```
</p>
</details>

<details>
<summary>Click to expand</summary>
<p>

```
The task factory "UtilPack.NuGet.MSBuild.NuGetTaskRunnerFactory" could not be loaded from the assembly "C:\Users\marian\Git\EarTrumpet\packages\UtilPack.NuGet.MSBuild.2.7.0\build\\net46\UtilPack.NuGet.MSBuild.dll". Could not load file or assembly 'System.ValueTuple, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
```
</p>
</details>

<details>
<summary>Click to expand</summary>
<p>

```
The tag 'Binding' does not exist in XML namespace 'clr-namespace:EarTrumpet.Extensions.EventBinding;assembly=EarTrumpet'. Line 18 Position 18.
```
</p>
</details>

**Comment by bramborman** [comment]
I tried updating the _GitVersionTask_ NuGet package and removing _UtilPack.NuGet.MSBuild_ as the new _GitVersionTask_ doesn't depend on it and am able to compile now even though it doesn't support .NET Framework 4.6.2 the app is targeting. It supports only 4.7.2 but maybe that's not a problem because it is run in the build process and not as part of the app...

**Comment by riverar** [comment]
@bramborman Fixed in `dev`, can you give that a whirl?
