### ISSUE TITLE
Can't unmute Microsoft Edge through EarTrumpet

### ISSUE THREAD

**Issue by 0xf0f** [File-New-Project/EarTrumpet#841]
## Description
EarTrumpet is able to mute Microsoft Edge but not unmute it.

## Steps to reproduce
1. Click on EarTrumpet system tray icon
2. Click on Microsoft Edge icon in the list to mute it. This should work.
3. Click on Microsoft Edge icon again to unmute it. This won't work. All tabs in the program remain muted and have to be unmuted manually through edge itself.

## Meta
* EarTrumpet version: 2.1.8.0
* Windows 10 version: 19042.928
* Edge version: 90.0.818.66

**Comment by riverar** [comment]
I can reproduce this, pasting log for my notes.

```
version: 2.1.8.186
runtimeMinutes: 0
gdiObjects: 87
userObjects: 49
globalGdiObjects: 1641
globalUserObjects: 1641
handleCount: 662
releaseStage: production
osVersionBuild: 22000.1.amd64fre.co_release.210604-1628
osArchitecture: 64 bit
processorCount: 8 core(s)
IsLightTheme: True
IsSystemLightTheme: True
IsRTL: False
IsTransparencyEnabled: True
UseAccentColor: False
AnimationsEnabled: False
IsHighContrast: False
HasIdentity: True
IsShuttingDown: False
Culture: en-US
CurrentUICulture: en-US
systemDpi: 96
taskbarDpi: 96
addons: 
region: US
--------------------------------------------------------------------
(Default Device) Remote Audio 100% Id: {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}
--------------------------------------------------------------------
  System Sounds
    (SystemSounds) (Inactive) 100% Id: {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
    AppId: System.SystemSoundsSession ProcessId: 0 Alive: True
    IconPath: C:\Windows\sysnative\audiosrv.dll,203
    GroupingParam: 8e85f426-d077-4487-a80b-25379a4ec441
--------------------------------------------------------------------
01:00:16.832 UI AudioDeviceManager-(Playback) Create
01:00:16.839 UI AudioDeviceManager-(Playback) Create Exit
01:00:16.845 UI TaskbarIconSource Changed: kind=NoDevice dpi=96 isSysLight=True isLegacy=False
01:00:16.853 UI IconHelper LoadIconForTaskbar C:\Windows\System32\SndVolSSO.dll,125 16x16
01:00:16.855  4   AudioDeviceManager-(Playback) OnDeviceAdded {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}
01:00:16.860  4   AudioDevice Create {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}
01:00:16.932  4   AudioDeviceSession Create msedge {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|\Device\HarddiskVolume4\Program Files (x86)\Microsoft\Edge\Application\msedge.exe%b{00000000-0000-0000-0000-000000000000}|1%b3092
01:00:16.937  4   FORCE-MOVE: Active {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45} -> {0.0.0.00000000}.{b315c1fd-6717-43dc-ae42-247456fdcbfd}
01:00:16.940  4   AudioDeviceSession Create *SystemSounds {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
01:00:16.948  4   System.NotImplementedException: The method or operation is not implemented.
   at EarTrumpet.Extensions.IPropertyStoreExtensions.GetValue[T](IPropertyStore propStore, PROPERTYKEY key) in D:\a\EarTrumpet\EarTrumpet\EarTrumpet\Extensions\IPropertyStoreExtensions.cs:line 19
   at EarTrumpet.DataModel.WindowsAudio.Internal.AudioDevice.ReadProperties() in D:\a\EarTrumpet\EarTrumpet\EarTrumpet\DataModel\WindowsAudio\Internal\AudioDevice.cs:line 196
01:00:17.110 UI FlyoutViewModel ChangeState Hidden
01:00:17.115 UI AudioDeviceManager-(Playback) QueryDefaultDevice
01:00:17.126 UI TaskbarIconSource Changed: kind=SpeakerThreeBars dpi=96 isSysLight=True isLegacy=False
01:00:17.127 UI IconHelper LoadIconForTaskbar C:\Windows\System32\SndVolSSO.dll,124 16x16
01:00:17.138 UI AddonResolver Load
01:00:17.141 UI AudioDeviceManager-(Recording) Create
01:00:17.141 UI AudioDeviceManager-(Recording) Create Exit
01:00:17.146 UI ProcessWatcher Clear
01:00:17.216 UI ShellNotifyIcon IsVisible True
01:00:17.217 UI AudioDeviceManager-(Recording) QueryDefaultDevice
01:00:17.222 UI AudioDeviceSessionCollection AddSession msedge {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|\Device\HarddiskVolume4\Program Files (x86)\Microsoft\Edge\Application\msedge.exe%b{00000000-0000-0000-0000-000000000000}|1%b3092
01:00:17.224 UI AudioDeviceSessionCollection AddSession *SystemSounds {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|#%b{A9EF3FD9-4240-455E-A4D5-F2B3301887B2}|1%b#
01:00:17.275 UI ImageEx LoadImage 24x24 C:\Windows\sysnative\audiosrv.dll,203
01:00:17.369 UI ImageEx LoadShellIcon 24x24 C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
01:00:24.197 UI FlyoutViewModel ChangeState Opening
01:00:24.201 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=65694, Size=[Left=0,Top=720,Right=1366,Bottom=768], Monitor=Screen[Bounds={X=0,Y=0,Width=1366,Height=768} WorkingArea={X=0,Y=0,Width=1366,Height=720} Primary=True DeviceName=\\.\DISPLAY129
01:00:24.253 UI FlyoutViewModel ChangeState Open
01:00:25.483 UI FlyoutViewModel ChangeState Closing_Stage1
01:00:25.498 UI FlyoutViewModel ChangeState Closing_Stage2
01:00:25.816 UI FlyoutViewModel ChangeState Hidden
01:00:26.867 UI FlyoutViewModel ChangeState Opening
01:00:26.870 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=65694, Size=[Left=0,Top=720,Right=1366,Bottom=768], Monitor=Screen[Bounds={X=0,Y=0,Width=1366,Height=768} WorkingArea={X=0,Y=0,Width=1366,Height=720} Primary=True DeviceName=\\.\DISPLAY129
01:00:26.883 UI FlyoutViewModel ChangeState Open
01:00:29.624 UI ImageEx LoadShellIcon 24x24 C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
01:00:32.920 11   AudioDeviceSession OnStateChanged Inactive msedge {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|\Device\HarddiskVolume4\Program Files (x86)\Microsoft\Edge\Application\msedge.exe%b{00000000-0000-0000-0000-000000000000}|1%b3092
01:00:32.921 UI AudioDeviceSessionCollection RemoveSession msedge {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|\Device\HarddiskVolume4\Program Files (x86)\Microsoft\Edge\Application\msedge.exe%b{00000000-0000-0000-0000-000000000000}|1%b3092
01:00:32.924 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=65694, Size=[Left=0,Top=720,Right=1366,Bottom=768], Monitor=Screen[Bounds={X=0,Y=0,Width=1366,Height=768} WorkingArea={X=0,Y=0,Width=1366,Height=720} Primary=True DeviceName=\\.\DISPLAY129
01:00:36.689 UI FlyoutViewModel ChangeState Closing_Stage1
01:00:36.718 UI FlyoutViewModel ChangeState Closing_Stage2
01:00:36.788 UI ShellNotifyIcon ShowContextMenu
01:00:36.815 UI ShellNotifyIcon ContextMenu.Opened
01:00:37.034 UI FlyoutViewModel ChangeState Hidden
01:00:37.545 UI ProcessWatcher Clear
01:00:37.547 UI SettingsWindow .ctor
01:00:37.705 UI ShellNotifyIcon ContextMenu.Closed
```

**Comment by riverar** [comment]
After you unmute Edge once (via Edge), subsequent mute/unmute from EarTrumpet works normally.

Log continues:
```
[...]
01:00:40.588 UI ProcessHelper StartNoThrow C:\Users\Rafael\AppData\Local\Temp\tmp43E9.tmp.txt
01:02:04.645 11   AudioDeviceSession OnStateChanged Active msedge {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|\Device\HarddiskVolume4\Program Files (x86)\Microsoft\Edge\Application\msedge.exe%b{00000000-0000-0000-0000-000000000000}|1%b3092
01:02:04.645 UI AudioDeviceSessionCollection AddSession msedge {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|\Device\HarddiskVolume4\Program Files (x86)\Microsoft\Edge\Application\msedge.exe%b{00000000-0000-0000-0000-000000000000}|1%b3092
01:02:04.713 UI ImageEx LoadShellIcon 24x24 C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
01:02:05.899 UI FlyoutViewModel ChangeState Opening
01:02:05.900 UI WindowsTaskbar Current: Location=Bottom, AutoHide=False, Taskbar=65694, Size=[Left=0,Top=720,Right=1366,Bottom=768], Monitor=Screen[Bounds={X=0,Y=0,Width=1366,Height=768} WorkingArea={X=0,Y=0,Width=1366,Height=720} Primary=True DeviceName=\\.\DISPLAY129
01:02:05.919 UI FlyoutViewModel ChangeState Open
01:02:06.843 16   AudioDeviceSession OnStateChanged Inactive msedge {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|\Device\HarddiskVolume4\Program Files (x86)\Microsoft\Edge\Application\msedge.exe%b{00000000-0000-0000-0000-000000000000}|1%b3092
01:02:07.739 11   AudioDeviceSession OnStateChanged Active msedge {3.0.0.00000001}.{6C26BA7D-F0B2-4225-B422-8168C5261E45}|\Device\HarddiskVolume4\Program Files (x86)\Microsoft\Edge\Application\msedge.exe%b{00000000-0000-0000-0000-000000000000}|1%b3092
01:02:27.188 UI FlyoutViewModel ChangeState Closing_Stage1
01:02:27.206 UI FlyoutViewModel ChangeState Closing_Stage2
01:02:27.521 UI FlyoutViewModel ChangeState Hidden
01:02:28.387 UI ShellNotifyIcon ShowContextMenu
01:02:28.410 UI ShellNotifyIcon ContextMenu.Opened
01:02:29.035 UI ShellNotifyIcon ContextMenu.Closed

```
